{% set name = "amostra" %}
{% set version = "1.0.1" %}
{% set sha256 = "b72f38171c4e14c4b8f6245375d44e9d704f848e5ea5265836f9c045919ecd74" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NSLS-II/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - doct
    - jsonschema
    - mongoquery
    - pymongo
    - pyyaml
    - requests
    - tornado
    - ujson

test:
  requires:
    - python {{ python_min }}
  imports:
    - amostra

about:
  home: https://nsls-ii.github.io/amostra
  license: BSD-3-Clause
  license_file: LICENSE
  summary: amostra is a collection of light-weight sample management classes
  dev_url: https://github.com/NSLS-II/amostra
  doc_url: https://nsls-ii.github.io/amostra

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
